[[data]]
image = "images/pastel-style"
title = "Pastel Style"
repo = "Linaqruf/pastel-anime-xl-lora"
weights = "pastel-anime-xl-latest.safetensors"
multiplier = 0.6
sample_prompt = "face focus, cute, masterpiece, best quality, 1girl, green hair, sweater, looking at viewer, upper body, beanie, outdoors, night, turtleneck"
sample_negative = "Standard"

[[data]]
image = "images/ufotable-style"
title = "Ufotable Style"
repo = "Linaqruf/ufotable-xl-lora"
weights = "ufotable_style_xl.safetensors"
multiplier = 0.4
sample_prompt = "face focus, cute, masterpiece, best quality, bokeh, breasts, 1girl, solo, looking at viewer, long hair, white ribbon, smile, school uniform,  bangs, black hair ribbon, swept bangs, sailor collar, serafuku, blush, ribbon, ahoge, brown eyes, long sleeves, collarbone, parted lips, sweater"
sample_negative = "Weighted"

[[data]]
image = "images/amelia-watson"
title = "Amelia Watson"
repo = "Linaqruf/amelia-watson-xl-lora"
weights = "amelia_watson_xl.safetensors"
multiplier = 0.5
sample_prompt = "face focus, masterpiece, best quality, amelia watson, bokeh, cute, 1girl, solo, monocle hair ornament, medium hair, brown eyewear, white shirt, red necktie, upper body, looking at viewer, blue eyes, leaf, plant"
sample_negative = "Weighted"

[[data]]
image = "images/furina"
title = "Furina"
repo = "Linaqruf/furina-xl-lora"
weights = "furina_xl.safetensors"
multiplier = 0.7
sample_prompt = "face focus, masterpiece, best quality, furina, bokeh, cute, 1girl, ahoge, ascot, blue eyes, blue gemstone, blue hair, blue headwear, blue jacket, gem, hair between eyes, hat, jacket, light blue hair, looking at viewer, multicolored hair, closed mouth, solo, top hat, white hair"
sample_negative = "Weighted"
